<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>FitAI | Home</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Segoe+UI&display=swap">
    <link rel="stylesheet" href="css/public.css">
    
</head>
<body>

<!-- 🧠 HEADER INCLUDE HERE -->
<jsp:include page="header.jsp" />

<div class="hero">
    <h2>Welcome to FitAI</h2>
    <p>Your AI-powered health and fitness partner. Personalized diet, workout, and progress tracking at your fingertips.</p>
    <div class="cta-buttons">
        <a href="/login">Login</a>
        <a href="/signup">Signup</a>
    </div>
</div>

<div class="sections">
    <div class="section">
        <h3>💡 About FitAI</h3>
        <p>
            FitAI is a smart fitness assistant that helps you with tailored health plans using artificial intelligence.
            Whether your goal is to gain, lose, or maintain weight — we’ve got you covered.
        </p>
    </div>

    <div class="section">
        <h3>🚀 Key Features</h3>
        <p>
            • AI-based BMI diet plans<br>
            • Budget-friendly supplement suggestions<br>
            • Visual progress tracking system<br>
            • Health tips generated by AI<br>
            • Workout guide with AI visuals<br>
            • Export plans to PDF for offline use
        </p>
    </div>

    <div class="section">
        <h3>✅ Why Choose FitAI?</h3>
        <p>
            • Clean UI and secure user experience<br>
            • Personalized health insights<br>
            • Made for students, professionals & gym lovers<br>
            • Developed by tech-driven fitness enthusiasts
        </p>
    </div>
</div>

<!-- 🔚 FOOTER INCLUDE HERE -->
<jsp:include page="footer.jsp" />

</body>
</html>
